# -*- coding: utf-8 -*-
import json, html, importlib.util
spec=importlib.util.spec_from_file_location("b","build-ocean.py")
import os, re
e=lambda s: html.escape(str(s),quote=True)
BASE="https://mombasafish.com"
NAV=[("index.html","Home"),("catalogue.html","Shop"),("fishguide.html","Fish Guide"),
     ("ask.html","Ask"),("recipes.html","Recipes"),("shimoni.html","Why Shimoni"),
     ("ocean.html","Ocean Explorers"),("wholesale.html","Wholesale"),("track.html","Track Order"),
     ("blog.html","Blog"),("about.html","About"),("ecosystem.html","Ecosystem")]
def head(title,desc,url,img,ld=None,up="",on=""):
    h=['<!DOCTYPE html>','<html lang="en">','<head>','<meta charset="UTF-8">',
     '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
     '<title>%s</title>'%e(title),'<meta name="description" content="%s">'%e(desc),
     '<link rel="canonical" href="%s">'%url,
     '<meta property="og:type" content="website"><meta property="og:locale" content="en_KE">',
     '<meta property="og:site_name" content="MombasaFish">',
     '<meta property="og:title" content="%s">'%e(title),
     '<meta property="og:description" content="%s">'%e(desc),
     '<meta property="og:url" content="%s">'%url,
     '<meta property="og:image" content="%s/images/%s">'%(BASE,img),
     '<meta name="twitter:card" content="summary_large_image">',
     '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
     '<link href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=IBM+Plex+Mono&family=Inter:wght@400;600;700&display=swap" rel="stylesheet">',
     '<link rel="icon" href="%simages/logo.jpg">'%up,'<link rel="stylesheet" href="%sstyle.css">'%up]
    for x in (ld or []): h.append('<script type="application/ld+json">%s</script>'%json.dumps(x,ensure_ascii=False))
    h+=['</head>','<body class="oe">',
     '<div class="annc">Fresh catch daily · Order on WhatsApp <a href="https://wa.me/254787668888">0787 668 888</a> · Pay with M-Pesa</div>',
     '<header class="hdr">',
     '  <a class="logo" href="%sindex.html"><img src="%simages/logo.jpg" alt="MombasaFish logo" width="34" height="34" style="width:34px;height:34px;border-radius:8px;object-fit:cover"><span class="wm">Mombasa<em>Fish</em></span></a>'%(up,up),
     '  <nav class="nav">']+['    <a href="%s%s"%s>%s</a>'%(up,u,' class="on"' if u==on else '',t) for u,t in NAV]+['  </nav>','</header>','']
    return h
def foot(up=""):
    return ['<footer>','  <div class="cols">',
     '    <div><h2>Ocean Explorers</h2><a href="%socean.html">Start here</a><a href="%socean/creatures.html">Marine creatures</a><a href="%socean/classroom.html">Ocean classroom</a><a href="%socean/quiz.html">Quiz &amp; certificate</a><a href="%socean/teachers.html">Parents &amp; teachers</a></div>'%(up,up,up,up,up),
     '    <div><h2>MombasaFish</h2><a href="%sindex.html">Home</a><a href="%scatalogue.html">Shop</a><a href="%sshimoni.html">Why Shimoni</a><a href="%spolicies.html">Policies &amp; privacy</a></div>'%(up,up,up,up),
     '    <div><h2>Contact</h2><a href="https://wa.me/254787668888">WhatsApp: 0787 668 888</a><a href="mailto:mombasafish@gmail.com">mombasafish@gmail.com</a></div>',
     '  </div>',
     '  <p class="fine"><span class="wmf">Mombasa<em>Fish</em></span> — Market · Media · Academy · Ocean · Exports<br>Ocean Explorers is free to use, in class or at home.<br>© 2026 MombasaFish</p>',
     '</footer>','','<script src="%sui.js" defer></script>'%up,
     '<!-- Cloudflare Web Analytics --><script type="module" src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon=\'{"token": "a0dfbad9d92441fe9afdaf972bb97acd"}\'></script><!-- End Cloudflare Web Analytics -->',
     '</body>','</html>']

Q=[
 ("An octopus has how many hearts?",["One","Two","Three"],2,"Three — two pump blood to the gills and one to the rest of the body."),
 ("Which of these is NOT a fish?",["Dolphin","Seahorse","Shark"],0,"A dolphin is a mammal. It breathes air, is born alive and drinks its mother's milk."),
 ("What is white sand on a coral beach mostly made of?",["Crushed shells","Parrotfish droppings","Volcanic rock"],1,"Parrotfish scrape algae off coral, digest it, and pass out the rock as fine white sand."),
 ("Why does coral turn white?",["It is dying of cold","It has pushed out the algae living inside it","It is old"],1,"Warm water makes coral expel the algae that feed it. That is bleaching, and the coral is starving."),
 ("What is the Swahili name for octopus?",["Pweza","Pomboo","Papa"],0,"Pweza. Pomboo is dolphin and papa is shark."),
 ("Which wind blows from the north-east from about November to March?",["Kusi","Kaskazi","Monsuni"],1,"The Kaskazi. The Kusi blows from the south-east, roughly April to October."),
 ("Seagrass is...",["A kind of seaweed","A true flowering plant","A coral"],1,"A true flowering plant with roots and seeds, which returned to the sea about a hundred million years ago."),
 ("Which parent seahorse carries the eggs?",["The mother","The father","Both take turns"],1,"The father. The female places her eggs in his pouch and he carries them until they hatch."),
 ("What decides whether turtle hatchlings are male or female?",["The mother","The temperature of the sand","The size of the egg"],1,"Sand temperature. Warmer sand produces more females."),
 ("How many bones does a shark have?",["None","About 200","More than a person"],0,"None. A shark's whole skeleton is cartilage — the bendy material in your ear."),
 ("Why do mangrove roots arch above the mud?",["To catch fish","So the tree can breathe at high tide","To look impressive"],1,"So the tree can take in air when the tide covers the mud."),
 ("Which is usually the more sustainable choice?",["A large old grouper","Sardines","Both the same"],1,"Sardines. They breed fast and in huge numbers, while a big grouper took many years to grow."),
]
quiz_ld={"@context":"https://schema.org","@type":"Quiz","name":"Ocean Explorer Quiz",
 "about":"Kenyan marine life, habitats and sustainable fishing","educationalLevel":"Primary and lower secondary",
 "isAccessibleForFree":True,"provider":{"@type":"Organization","name":"MombasaFish"}}
p=head("Ocean Explorer Quiz & Certificate | MombasaFish",
 "Twelve questions about Kenya's ocean — fish, turtles, corals, tides and the monsoon. Score eight or more and print your Ocean Explorer certificate.",
 BASE+"/ocean/quiz","pweza.jpg",[quiz_ld],"../","ocean.html")
p+=['<div class="wrap">',
 '<nav class="crumb" aria-label="Breadcrumb"><a href="../index.html">Home</a> › <a href="../ocean.html">Ocean Explorers</a> › <span>Quiz</span></nav>',
 '<section>','  <span class="kick">Section four</span>',
 '  <h1 class="sec">The Ocean Explorer <span>quiz</span></h1>',
 '  <p class="sec-sub">Twelve questions. Every answer is somewhere in Ocean Explorers, and every one is explained after you choose. Get eight or more and you can print your certificate.</p>',
 '  <p class="oeprivacy"><b>Nothing you type here leaves your device.</b> There is no sign-up, no account and no tracking. Your name is only used to draw the certificate on your own screen, and it disappears when you close the page.</p>',
 '  <div id="quiz" class="oequiz">']
for i,(qq,opts,ans,exp) in enumerate(Q):
    p+=['    <div class="oeq" data-a="%d" id="q%d">'%(ans,i+1),
     '      <p class="oeqn">Question %d of %d</p>'%(i+1,len(Q)),
     '      <h2>%s</h2>'%e(qq),
     '      <div class="oeopts">']
    for j,o in enumerate(opts):
        p.append('        <button type="button" data-i="%d">%s</button>'%(j,e(o)))
    p+=['      </div>','      <p class="oeexp">%s</p>'%e(exp),'    </div>']
p+=['  </div>','',
 '  <div class="oeresult" id="result" hidden>',
 '    <h2>Your score: <span id="score">0</span> / %d</h2>'%len(Q),
 '    <p id="verdict"></p>',
 '    <div id="certwrap" hidden>',
 '      <label for="cname">Write your name for the certificate</label>',
 '      <input id="cname" type="text" maxlength="34" placeholder="Your name" autocomplete="off">',
 '      <button type="button" class="oebtn hot" id="makecert">Make my certificate</button>',
 '    </div>',
 '    <button type="button" class="oebtn" id="again">Try again</button>',
 '  </div>','',
 '  <div class="cert" id="cert" hidden>',
 '    <div class="certinner">',
 '      <p class="certk">MombasaFish · Ocean Explorers</p>',
 '      <h2>Certificate of Ocean Exploring</h2>',
 '      <p class="certfor">awarded to</p>',
 '      <p class="certname" id="certname">—</p>',
 '      <p class="certbody">for learning about the fish, creatures and habitats of the Kenyan coast, and for understanding that an ocean looked after today is an ocean that feeds people tomorrow.</p>',
 '      <p class="certmeta"><span id="certscore"></span> · <span id="certdate"></span></p>',
 '      <p class="certsign">Shimoni · Kwale County · Kenya</p>',
 '    </div>',
 '    <button type="button" class="oebtn" id="printcert">Print or save as PDF</button>',
 '  </div>',
 '</section>','</div>','',
 '<script>',
 '(function(){',
 '  var qs=[].slice.call(document.querySelectorAll(".oeq")), score=0, done=0;',
 '  var res=document.getElementById("result"), cw=document.getElementById("certwrap");',
 '  qs.forEach(function(q){',
 '    var ans=+q.dataset.a;',
 '    q.querySelectorAll(".oeopts button").forEach(function(b){',
 '      b.addEventListener("click",function(){',
 '        if(q.classList.contains("answered")) return;',
 '        q.classList.add("answered");',
 '        var right=+b.dataset.i===ans;',
 '        b.classList.add(right?"right":"wrong");',
 '        if(!right) q.querySelector(\'.oeopts button[data-i="\'+ans+\'"]\').classList.add("right");',
 '        if(right) score++;',
 '        done++;',
 '        if(done===qs.length) finish();',
 '      });',
 '    });',
 '  });',
 '  function finish(){',
 '    document.getElementById("score").textContent=score;',
 '    var v=document.getElementById("verdict");',
 '    if(score>=8){ v.textContent="Well done — that is Ocean Explorer standard."; cw.hidden=false; }',
 '    else { v.textContent="Close. Read a little more and try again — you need eight to earn the certificate."; cw.hidden=true; }',
 '    res.hidden=false; res.scrollIntoView({behavior:"smooth",block:"center"});',
 '  }',
 '  var mk=document.getElementById("makecert");',
 '  if(mk) mk.addEventListener("click",function(){',
 '    var n=(document.getElementById("cname").value||"").trim();',
 '    if(!n){ document.getElementById("cname").focus(); return; }',
 '    document.getElementById("certname").textContent=n;',
 '    document.getElementById("certscore").textContent="Scored "+score+" out of %d";' % len(Q),
 '    document.getElementById("certdate").textContent=new Date().toLocaleDateString("en-KE",{year:"numeric",month:"long",day:"numeric"});',
 '    var c=document.getElementById("cert"); c.hidden=false; c.scrollIntoView({behavior:"smooth"});',
 '  });',
 '  var pr=document.getElementById("printcert");',
 '  if(pr) pr.addEventListener("click",function(){ window.print(); });',
 '  var ag=document.getElementById("again");',
 '  if(ag) ag.addEventListener("click",function(){ location.reload(); });',
 '})();',
 '</script>']+foot("../")
open("ocean/quiz.html","w",encoding="utf-8").write("\n".join(p))

# ---------------- TEACHERS ----------------
p=head("Parents & Teachers — free ocean lesson ideas for Kenyan classrooms | MombasaFish",
 "Free lesson ideas, discussion questions and classroom activities about Kenya's ocean — reefs, mangroves, tides, the monsoon and sustainable fishing.",
 BASE+"/ocean/teachers","shimoni-beach.jpg",None,"../","ocean.html")
p+=['<div class="wrap">',
 '<nav class="crumb" aria-label="Breadcrumb"><a href="../index.html">Home</a> › <a href="../ocean.html">Ocean Explorers</a> › <span>Parents &amp; teachers</span></nav>',
 '<section>','  <span class="kick">Section five</span>',
 '  <h1 class="sec">Parents &amp; <span>teachers</span></h1>',
 '  <p class="sec-sub">Everything here is free to use, print and photocopy for a class. No login, no sign-up, and nothing about your pupils is collected — the quiz and certificate run entirely on the device.</p>','',
 '  <div class="oelessons">',
 '    <article class="oeles"><span class="oenum">Activity 1</span><h2>The three habitats</h2>',
 '      <p><b>Ages 6–10 · 30 minutes.</b> Draw a cross-section of the coast from beach to open sea: mangrove creek, seagrass meadow, coral reef, deep water. Ask pupils to place animals where they belong — crab in the mangrove, tafi in the seagrass, changu on the reef, tuna in the deep.</p>',
 '      <p><b>Discussion:</b> what happens to the reef fish if the seagrass nursery disappears? Follow the chain out loud.</p></article>',
 '    <article class="oeles"><span class="oenum">Activity 2</span><h2>Tides on the wall</h2>',
 '      <p><b>Ages 9–13 · one week.</b> Find the tide table for your nearest port and chart high and low tides for seven days on a wall. Ask pupils to predict day eight before checking.</p>',
 '      <p><b>Discussion:</b> why two high tides a day rather than one? Use a ball and a torch to show the two bulges.</p></article>',
 '    <article class="oeles"><span class="oenum">Activity 3</span><h2>Fish or not a fish?</h2>',
 '      <p><b>Ages 6–10 · 20 minutes.</b> Sort cards into two piles. Dolphin, turtle, octopus, crab, seahorse, shark, sea star, squid. Only the seahorse, shark and the true fish belong in one pile.</p>',
 '      <p><b>Discussion:</b> what makes a fish a fish? Gills, fins, scales, cold blood, eggs — then look at which rules the seahorse and the shark break.</p></article>',
 '    <article class="oeles"><span class="oenum">Activity 4</span><h2>The closed area experiment</h2>',
 '      <p><b>Ages 11–15 · 45 minutes.</b> Use counters as fish in two identical "seas". Fish one every round; leave the other closed for three rounds, then fish it. Double the remaining counters between rounds to represent breeding.</p>',
 '      <p><b>Discussion:</b> which sea ends up with more fish, and why? This is exactly the logic behind octopus closures on the Kenyan coast.</p></article>',
 '    <article class="oeles"><span class="oenum">Activity 5</span><h2>Where does our plastic go?</h2>',
 '      <p><b>Ages 9–15 · one week.</b> Have pupils log every piece of plastic they use for two days, then trace the route from bin to drain to river to sea for three of them.</p>',
 '      <p><b>Project:</b> a beach or schoolyard clean-up, sorting and counting the categories found. Counting turns tidying into science.</p></article>',
 '    <article class="oeles"><span class="oenum">Activity 6</span><h2>Interview a fisherman</h2>',
 '      <p><b>Ages 11–15.</b> If you are near the coast, invite a local fisherman or a Beach Management Unit member to class. Pupils prepare five questions in advance.</p>',
 '      <p><b>Why it works:</b> knowledge that has never been written down is the most interesting thing in the room, and it is sitting with the person who goes out at 04:30.</p></article>',
 '  </div>','',
 '  <div class="oenote">',
 '    <h2>How to use this with a class</h2>',
 '    <p><b>Print it.</b> Every page here prints cleanly in black and white. Use your browser\'s print function; the navigation and buttons drop away automatically.</p>',
 '    <p><b>No accounts, no data.</b> Pupils do not sign in. The quiz score and the certificate name stay in the browser and are gone when the tab closes. Nothing about a child reaches us or anyone else.</p>',
 '    <p><b>Corrections welcome.</b> If you are a teacher or a marine scientist and you find something wrong here, please tell us on <a href="https://wa.me/254787668888">WhatsApp</a> and we will fix it. Accuracy matters more to us than looking clever.</p>',
 '  </div>','',
 '  <p style="margin-top:1.6rem"><a class="oebtn" href="../ocean.html">← Back to Ocean Explorers</a> <a class="oebtn hot" href="quiz.html">The quiz</a></p>',
 '</section>','</div>','']+foot("../")
open("ocean/teachers.html","w",encoding="utf-8").write("\n".join(p))
print("quiz + teachers written · quiz questions:",len(Q))
