# -*- coding: utf-8 -*-
"""MombasaFish — species/product content source. Edit here, then run build-fish-pages.py."""
import json

# Shared defaults by category
DEF = {
 "Whole Fish": dict(
   meth="Handline and small-net fishing from open wooden boats",
   loc="Shimoni and the Pemba Channel, Kwale County",
   store="Keep on ice or in the coldest part of the fridge (0–4 °C) and cook within 2 days of delivery. To freeze, pat dry, wrap tightly and freeze at −18 °C; use within 3 months. Never refreeze fish that has thawed.",
   shelf="2 days refrigerated · 3 months frozen"),
 "Prawns": dict(
   meth="Small-boat trawl and creek net fishing",
   loc="Shimoni creeks and the inshore waters of Kwale County",
   store="Keep prawns on ice and cook within 1–2 days. Shell-on keeps better than peeled. Freeze at −18 °C for up to 3 months; thaw in the fridge, never on the counter.",
   shelf="1–2 days refrigerated · 3 months frozen"),
 "Shellfish &amp; More": dict(
   meth="Hand-gathered and small-boat fishing",
   loc="The reefs, creeks and rock shelves around Shimoni",
   store="Shellfish are the most perishable thing we sell. Keep cold and cook the day of delivery where possible, and within 24 hours at the latest.",
   shelf="1 day refrigerated"),
 "Fillets": dict(
   meth="Handline fishing; filleted by hand at our counter",
   loc="Shimoni and the Pemba Channel, Kwale County",
   store="Fillets have no skin or bone to protect them. Keep at 0–4 °C, cook within 1–2 days, or freeze immediately at −18 °C for up to 3 months.",
   shelf="1–2 days refrigerated · 3 months frozen"),
 "Dried, Sea Moss &amp; Honey": dict(
   meth="Sun-dried and hand-processed",
   loc="The Kenyan south coast",
   store="Store in a sealed container in a cool, dry, dark place. No refrigeration needed.",
   shelf="6–12 months sealed and dry"),
 "Dried Prawns": dict(
   meth="Sun-dried after landing",
   loc="Shimoni and the Kwale coast",
   store="Airtight container, cool and dry, away from sunlight. If your kitchen is humid, keep them in the fridge.",
   shelf="6 months sealed and dry"),
}

# Per-product content. nutrition = approximate per 100 g raw edible portion.
C = {
"Emperor Fish": dict(sci="Lethrinus spp.", fam="Lethrinidae (emperors)",
  nut="~110 kcal · 21 g protein · 2 g fat · high in phosphorus and selenium",
  health="Lean, high-protein white fish with very little fat. A sensible everyday choice for families, and mild enough for children and older people who dislike strong fish.",
  cook="Fry whole after scoring the sides; grill over charcoal; or simmer in coconut sauce for samaki wa kupaka. Firm enough to hold together in a curry.",
  pair="Coconut rice, kachumbari, ugali",
  faq=[("Does changu have many bones?","No — changu is one of the easiest reef fish to eat. It has a simple bone structure and few fine pin bones, which is exactly why it is the family favourite on this coast."),
       ("What size do they come in?","Typically 0.5–1.5 kg per fish. Tell us your preferred size and we will pick to match."),
       ("Can I have it filleted?","Yes. Choose your preparation at checkout — scaled, gutted, filleted, steaked or left whole.")]),
"Tuna Fish": dict(sci="Thunnus albacares / Katsuwonus pelamis", fam="Scombridae (tuna and mackerel)",
  nut="~130 kcal · 24 g protein · 3 g fat · rich in omega-3, vitamin D, vitamin B12 and selenium",
  health="One of the best sources of long-chain omega-3 fatty acids you can buy on this coast, along with high-quality protein and vitamin B12.",
  cook="Sear hot and fast — 1–2 minutes a side for a 2 cm steak, leaving the centre pink. Overcooked tuna turns dry and grey. Also excellent grilled over charcoal or served raw, sashimi-style, when very fresh.",
  pair="Lime, ginger, soy, charred vegetables",
  faq=[("Is your tuna safe to eat raw?","Tuna landed and iced the same morning is the only tuna worth eating raw. Tell us on WhatsApp that you intend to serve it raw and we will pick and handle it accordingly. If you are pregnant, immunocompromised, very young or elderly, cook it through."),
       ("Yellowfin or skipjack?","Both come off the Shimoni boats depending on the day. Yellowfin is the larger, deeper-red steak fish; skipjack is smaller and stronger in flavour."),
       ("How thick are the steaks?","We cut to about 2–3 cm as standard. Say the word and we will cut thicker or thinner.")]),
"King Fish": dict(sci="Scomberomorus commerson", fam="Scombridae (Spanish mackerel)",
  nut="~105 kcal · 22 g protein · 2 g fat · good source of omega-3, niacin and vitamin B12",
  health="Firm, meaty and relatively lean for an oily fish. A strong protein source that also delivers useful omega-3.",
  cook="The classic Swahili biryani fish — the chunks hold their shape through a long, spiced cook. Also outstanding as thick charcoal-grilled steaks, or shallow-fried in a spiced flour crust.",
  pair="Biryani spice, tamarind, coconut, pilipili",
  faq=[("Why is nguru the biryani fish?","Because it does not fall apart. The flesh is dense and holds together through the layering and steaming that biryani needs, where a softer fish would disintegrate into the rice."),
       ("Is nguru bony?","Very little. It has a central bone and no significant pin bones, so steaks are almost bone-free."),
       ("What is the usual size?","Nguru run large — often 3–8 kg whole. Most customers buy it cut into steaks. Tell us how many kilos and how you want it cut.")]),
"Red Snapper": dict(sci="Lutjanus spp.", fam="Lutjanidae (snappers)",
  nut="~100 kcal · 21 g protein · 1.3 g fat · high in selenium and vitamin B12",
  health="Very lean white fish, high in protein and low in saturated fat.",
  cook="Grill or bake whole with nothing more than salt, lime and oil — snapper is a fish that rewards restraint. Also excellent pan-fried in fillets, skin on, for crisp skin.",
  pair="Lime, garlic, parsley, olive oil, simple salads",
  faq=[("Why is snapper more expensive filleted?","Filleting a whole snapper yields roughly 40–45% of its live weight in boneless meat, so one kilo of fillet takes over two kilos of whole fish, plus the labour of cutting it."),
       ("Skin on or off?","Your choice — say which at checkout. Skin on is better for pan-frying and grilling; skin off suits curries and stews."),
       ("Is it really red?","The skin is rose-pink to red; the flesh is white and firm. Colour fades slightly with time on ice, which is normal.")]),
"Trevally Fish": dict(sci="Caranx spp.", fam="Carangidae (jacks and trevallies)",
  nut="~120 kcal · 22 g protein · 3 g fat · good source of omega-3 and potassium",
  health="A muscular, active fish with denser flesh and more natural oil than reef whitefish.",
  cook="Handles bold seasoning better than almost anything else on the slab. Deep-fry in a spiced crust, grill over charcoal, or cook long in a heavily spiced curry.",
  pair="Pilipili, tamarind, heavy spice, coconut",
  faq=[("Is kolekole strong-tasting?","Stronger than changu or tewa, milder than tuna. It is the fish to choose if you find white fish bland."),
       ("Good for grilling?","Excellent. The dense flesh holds together on a grate where softer fish break up.")]),
"Grouper Fish": dict(sci="Epinephelus spp.", fam="Serranidae (groupers)",
  nut="~92 kcal · 20 g protein · 1 g fat · high in selenium, low in fat",
  health="One of the leanest fish we sell — almost pure protein, very low fat.",
  cook="The mchuzi wa samaki classic. Large white flakes that soak up a coconut-and-tomato curry. Also good fried, though it is almost too lean for the grill.",
  pair="Coconut curry, tomato, coriander, ugali",
  faq=[("Why is tewa good for curry?","It flakes into large, clean pieces that absorb sauce rather than dissolving into it."),
       ("Is it bony?","Few bones and a simple structure — easy eating.")]),
"Sail Fish": dict(sci="Istiophorus platypterus", fam="Istiophoridae (billfish)",
  nut="~110 kcal · 23 g protein · 2 g fat · rich in protein, niacin and selenium",
  health="Very high protein, very low fat — a big-game fish with lean, steak-like flesh.",
  cook="Treat it like tuna. Thick steaks, seared hot and fast or grilled over charcoal, served on the rare side of done. It dries out quickly if overcooked.",
  pair="Lime, black pepper, charred onion",
  faq=[("Is sailfish like tuna?","Similar texture and steak cut, slightly paler and leaner. Cook it the same way and do not overdo it."),
       ("Can it be eaten raw?","We do not recommend it for billfish. Cook sailfish through or to medium at least.")]),
"Swordfish": dict(sci="Xiphias gladius", fam="Xiphiidae",
  nut="~145 kcal · 23 g protein · 5 g fat · rich in selenium, vitamin D and omega-3",
  health="A meaty, satisfying fish with more fat than sailfish and a good omega-3 profile. Like all large, long-lived predatory fish, swordfish accumulates more mercury than small species — an occasional choice rather than a weekly one, and one that pregnant women and young children are usually advised to avoid.",
  cook="Thick steaks on the charcoal. Swordfish is dense enough to behave like beef on a grill — do not move it until it releases.",
  pair="Lemon, oregano, olive oil, grilled vegetables",
  faq=[("Is swordfish safe to eat?","For most adults, in moderation, yes. Because it is a large predator it carries more mercury than small fish, so most health authorities advise pregnant women and young children to choose smaller species such as sardines, mackerel or changu instead."),
       ("How should I cook it?","Thick, over charcoal, and no more than medium. It is a lean, dense fish that turns dry when overcooked.")]),
"Cobia": dict(sci="Rachycentron canadum", fam="Rachycentridae",
  nut="~155 kcal · 21 g protein · 7 g fat · high in omega-3 and vitamin B12",
  health="Richer and fattier than most fish on this coast, with a correspondingly high omega-3 content.",
  cook="Rich enough to grill without drying, firm enough to cube for skewers. Also excellent smoked. Chefs prize it because it behaves like a premium fish at a coastal price.",
  pair="Citrus, chilli, smoked paprika",
  faq=[("Why do restaurants like songoro?","Firm white flesh, high fat, big clean fillets and almost no waste. It cooks like an expensive fish."),
       ("Is it oily?","Moderately — closer to salmon than to changu, but far milder in flavour.")]),
"Parrot Fish": dict(sci="Scarus spp.", fam="Scaridae (parrotfishes)",
  nut="~95 kcal · 20 g protein · 1.5 g fat · lean, high in protein",
  health="Lean, sweet white flesh — very mild and easy for children.",
  cook="Fry whole or steam with ginger and spring onion. Pono is delicate; it does not want a fierce charcoal grill or heavy spice.",
  pair="Ginger, spring onion, light coconut sauce",
  faq=[("Is pono sweet?","Yes — it is one of the sweetest, mildest reef fish, which is why it is popular with children."),
       ("Can I grill it?","You can, but gently. Pono is soft-fleshed and can break up on a grate. Frying whole suits it better.")]),
"Rabbit Fish": dict(sci="Siganus sutor", fam="Siganidae (rabbitfishes)",
  nut="~100 kcal · 19 g protein · 2 g fat · good source of protein and phosphorus",
  health="A lean, everyday fish and one of the most sustainable choices on the slab — tafi is abundant, fast-growing and central to the small-boat fishery.",
  cook="Fry whole, or grill. A staple of the coastal kitchen, best kept simple with salt, lime and pilipili.",
  pair="Ugali, kachumbari, lime",
  faq=[("Is tafi bony?","It has more fine bones than changu, but coastal families eat it whole and pick around them. Ask for fillets if bones are a concern."),
       ("Why is it cheaper?","Because it is abundant and lands in good numbers. Price here reflects supply, not quality.")]),
"Red Mullet": dict(sci="Parupeneus / Upeneus spp.", fam="Mullidae (goatfishes)",
  nut="~110 kcal · 19 g protein · 3.5 g fat · good source of iron and B vitamins",
  health="Small, flavourful fish eaten whole — which means you get more minerals than from a fillet.",
  cook="Fry whole and crisp. Mkundaji has a distinctive, almost shellfish-like sweetness that is lost if you smother it in spice.",
  pair="Salt, lime, chilli, fried cassava",
  faq=[("Why is mkundaji special?","It has a sweet, almost prawn-like flavour that no other fish on the slab matches — a chef's fish."),
       ("What size are they?","Small — usually 150–400 g each, so several to a kilo.")]),
"Shark Steak": dict(sci="Carcharhinus spp.", fam="Carcharhinidae (requiem sharks)",
  nut="~130 kcal · 21 g protein · 4.5 g fat · high in protein and vitamin B12",
  health="Dense, meaty and boneless — a substantial protein source. As a large predator, shark carries higher mercury than small fish, so it is best eaten occasionally rather than weekly, and is generally not advised during pregnancy.",
  cook="Cut into cubes for a heavily spiced curry, or grill as steaks. Soak in lime or milk for 30 minutes first — it firms the flesh and removes any ammonia note.",
  pair="Heavy spice, tamarind, coconut, lime",
  faq=[("Why soak shark before cooking?","Sharks retain urea in their flesh, which can turn to ammonia over time. A 30-minute soak in lime juice, vinegar or milk removes it completely."),
       ("Is shark bony?","No — sharks have cartilage, not bone. Shark steak is entirely boneless, which is why it is popular with children and older people."),
       ("Is it sustainable?","It is landed as part of the mixed small-boat catch on this coast rather than targeted industrially. We do not buy or sell any protected or listed species.")]),
"Sardines": dict(sci="Sardinella spp.", fam="Clupeidae (sardines and herrings)",
  nut="~165 kcal · 21 g protein · 9 g fat · exceptional omega-3, calcium, vitamin D and B12",
  health="Gram for gram and shilling for shilling, the most nutritious fish we sell. Eaten whole with the bones, sardines deliver more calcium than a glass of milk, plus very high omega-3 and vitamin D. As a small, short-lived fish they also carry the least mercury.",
  cook="Fry whole and crisp until the bones are edible. Also excellent grilled over charcoal, or stewed with tomato and onion.",
  pair="Ugali, tomato, onion, lime, chilli",
  faq=[("Should I eat the bones?","Yes — that is the point. Fried until crisp, sardine bones are soft and edible, and they are where the calcium is."),
       ("Are sardines healthier than tuna?","For omega-3 per shilling, considerably. They also carry far less mercury because they are small and short-lived."),
       ("How many to a kilo?","Roughly 15–25, depending on the day's size.")]),
"Anchovies": dict(sci="Stolephorus spp.", fam="Engraulidae (anchovies)",
  nut="~130 kcal · 20 g protein · 5 g fat · very high in calcium, omega-3 and B12",
  health="Tiny, cheap and nutritionally dense. Eaten whole, they are one of the best calcium sources available, and among the lowest-mercury fish in the sea.",
  cook="Fry crisp in seasoned flour and eat like a snack. Also stewed with tomato, or dried and used to build depth in a stew.",
  pair="Ugali, tomato stew, lime, chilli",
  faq=[("How are uwono different from simusimu?","Uwono (anchovies) are smaller and finer; simusimu (sardines) are larger and oilier. Both are eaten whole."),
       ("Do I need to clean them?","At this size, no. Fry them as they are.")]),
"Indian Mackerel": dict(sci="Rastrelliger kanagurta", fam="Scombridae",
  nut="~150 kcal · 22 g protein · 7 g fat · very high in omega-3, vitamin D and B12",
  health="An oily fish with an omega-3 content close to salmon at a fraction of the price. One of the best-value nutritional buys on the entire slab.",
  cook="Grill over charcoal, fry whole, or curry. The natural oil keeps it moist and forgiving — a hard fish to overcook.",
  pair="Coconut, tamarind, pilipili, ugali",
  faq=[("Is una oily?","Yes, pleasantly so — which is where the omega-3 lives and why it grills so well."),
       ("Is it strong-tasting?","Fuller than white reef fish, but far milder than a European mackerel. Fresh una is clean-tasting.")]),
"Salmon": dict(sci="Salmo salar", fam="Salmonidae", imported=True,
  meth="Farmed and imported — not caught by our boats",
  loc="Imported. Every other product on this site is Indian Ocean and traceable to Shimoni; salmon is the one exception, and we say so plainly.",
  nut="~200 kcal · 20 g protein · 13 g fat · very high in omega-3, vitamin D and B12",
  health="Rich, buttery and exceptionally high in omega-3 and vitamin D.",
  cook="Sear skin-side down for crisp skin, roast, or serve raw as sashimi. Salmon is forgiving — but pull it while the centre is still slightly translucent.",
  pair="Dill, lemon, soy, ginger, butter",
  faq=[("Is this salmon from the Indian Ocean?","No. Salmon is a cold-water fish and does not live in these waters. Ours is imported, and we label it clearly so our traceability claim on everything else stays honest."),
       ("Why is it so much more expensive?","Because it is imported and cold-chained the whole way. If you want the same omega-3 for a sixth of the price, buy una — Indian mackerel — instead.")]),
"Octopus": dict(sci="Octopus cyanea", fam="Octopodidae",
  nut="~82 kcal · 15 g protein · 1 g fat · very high in iron, copper, selenium and B12",
  health="Extremely lean, very high in protein, and one of the richest sources of iron and vitamin B12 in the sea.",
  cook="The rule is fast or slow, never in between. Either simmer 45–60 minutes until a knife slides in easily, or char it hot for 3–4 minutes. Anything between makes it rubbery. Coastal cooks tenderise by beating it or freezing it first — freezing breaks the fibres and genuinely works.",
  pair="Coconut curry, lime, chilli, garlic, potatoes",
  faq=[("Why does my octopus come out rubbery?","You cooked it in the middle range. Under 10 minutes or over 45 — nothing between."),
       ("Does freezing help?","Yes. Ice crystals break down the muscle fibres. A frozen-then-thawed octopus is genuinely more tender than a fresh one."),
       ("Do you clean it?","Yes — cleaned and ready to cook unless you ask otherwise.")]),
"Calamari · Squid": dict(sci="Uroteuthis duvaucelii / Sepioteuthis lessoniana", fam="Loliginidae",
  nut="~92 kcal · 16 g protein · 1.4 g fat · high in protein, phosphorus and B12",
  health="Very lean and high in protein.",
  cook="Same rule as octopus: 2 minutes hot, or 30 minutes slow. Rings for frying, tubes for stuffing, whole for the grill.",
  pair="Garlic, chilli, lime, aioli, coconut curry",
  faq=[("Rings or tubes?","Tell us at checkout. Rings are ready for the fryer; whole tubes are better for stuffing or grilling."),
       ("Fresh or frozen?","Landed fresh. As with octopus, a spell in the freezer actually improves tenderness.")]),
"Crab": dict(sci="Scylla serrata", fam="Portunidae (mud crab)",
  meth="Trap and hand-gathered from the mangrove creeks",
  loc="The mangrove creeks around Shimoni and Vanga, Kwale County",
  nut="~85 kcal · 18 g protein · 1 g fat · high in zinc, copper, selenium and B12",
  health="Lean, sweet and exceptionally high in zinc and selenium.",
  cook="Steam or boil 12–15 minutes per kilo, then crack at the table. Also outstanding in a coconut curry, or grilled split with garlic butter.",
  pair="Garlic butter, coconut, chilli, lime",
  faq=[("Are they live?","We supply them fresh and iced. If you want live crab for a specific event, ask on WhatsApp and we will try to arrange it."),
       ("How much crab per person?","Allow 400–500 g of whole crab per person as a main course — there is a lot of shell."),
       ("What is mud crab?","Scylla serrata — the big-clawed mangrove crab of the East African coast, and the finest eating crab in these waters.")]),
"Lobster": dict(sci="Panulirus spp.", fam="Palinuridae (spiny lobster)",
  meth="Hand-caught by divers and traps on the reef",
  loc="The reefs off Shimoni and Wasini Island",
  nut="~90 kcal · 19 g protein · 1 g fat · very high in selenium, zinc and B12",
  health="Very lean, very high protein, and rich in selenium and zinc.",
  cook="Split lengthwise, brush with garlic butter and grill shell-side down 6–8 minutes. Do not boil a good lobster to death — the tail is done the moment it turns opaque.",
  pair="Garlic butter, lime, chilli, coconut rice",
  faq=[("Is this the same as Maine lobster?","No — this is Indian Ocean spiny lobster, which has no large front claws. All the meat is in the tail, and it is sweeter than cold-water lobster."),
       ("How much per person?","One 400–500 g lobster per person as a main course."),
       ("Are they in season all year?","Availability varies with the monsoon and with closed-season rules. Message us for what is landing this week.")]),
"Oysters": dict(sci="Saccostrea cucullata", fam="Ostreidae (rock oysters)",
  meth="Hand-gathered from rock shelves at low tide",
  loc="The rocky shores of the Kenyan south coast",
  nut="~68 kcal · 7 g protein · 2 g fat · extraordinarily high in zinc, plus iron, copper and B12",
  health="The single richest natural source of zinc of any food. Also high in iron, copper and vitamin B12.",
  cook="Raw on ice with lime and a drop of pilipili, or grilled in the shell with garlic butter until they just open.",
  pair="Lime, pilipili, garlic butter, cold beer",
  faq=[("Are they safe to eat raw?","Raw shellfish always carries some risk. Ours are gathered and iced fresh, but anyone pregnant, immunocompromised, elderly or very young should eat oysters cooked rather than raw."),
       ("How many per person?","Six to twelve as a starter."),
       ("How do I know one is bad?","Discard any that is already open and does not close when tapped, or that smells of anything but clean sea.")]),
"Mussels": dict(sci="Perna perna", fam="Mytilidae",
  meth="Hand-gathered from rocks and reef at low tide",
  loc="The rocky south coast around Shimoni",
  nut="~86 kcal · 12 g protein · 2 g fat · very high in iron, manganese, selenium and B12",
  health="One of the best iron sources in the sea and remarkably high in vitamin B12.",
  cook="Steam in a covered pot with garlic, chilli and coconut milk for 5–6 minutes until they open. Discard any that stay shut.",
  pair="Coconut, garlic, chilli, bread for the broth",
  faq=[("How do I clean them?","Scrub the shells and pull away the beard. Discard any open shell that will not close when tapped."),
       ("What if some do not open?","Throw those away — an unopened mussel after cooking should not be eaten.")]),
"White Clams": dict(sci="Venerid clams", fam="Veneridae",
  meth="Hand-dug from sand flats at low tide",
  loc="The tidal flats of the Kenyan south coast",
  nut="~86 kcal · 15 g protein · 1 g fat · exceptionally high in iron and vitamin B12",
  health="Clams contain more vitamin B12 per gram than almost any other food, and are extremely high in iron.",
  cook="Purge in salted water for an hour to release sand, then steam with garlic and chilli for 5 minutes until they open.",
  pair="Garlic, white wine or lime, coconut, pasta, rice",
  faq=[("How do I get the sand out?","Sit them in cold salted water for an hour before cooking. They will spit the sand out themselves."),
       ("How many per person?","About 250–300 g per person as a starter, 500 g as a main.")]),
"Prawns Jumbo": dict(sci="Penaeus monodon", fam="Penaeidae",
  nut="~99 kcal · 21 g protein · 1 g fat · very high in selenium, iodine and B12",
  health="Very lean and high in protein. Prawns contain dietary cholesterol but almost no saturated fat, which is the number that matters more for most people.",
  cook="The showpiece size. Split down the back, grill shell-on with garlic butter, 3 minutes a side. Shell-on protects the meat and carries the flavour.",
  pair="Garlic butter, lime, chilli, coconut rice",
  faq=[("How many jumbo prawns to a kilo?","Roughly 12–16, depending on the day."),
       ("Head on or off?","Head on as standard — the heads carry most of the flavour. Ask for headless if you prefer."),
       ("Can you peel them?","Yes. Choose peeled and deveined at checkout. Note that peeling loses about 40% of the weight to shell and head.")]),
"Prawns King": dict(sci="Penaeus spp.", fam="Penaeidae",
  nut="~99 kcal · 21 g protein · 1 g fat · very high in selenium, iodine and B12",
  health="Lean, high-protein and rich in selenium and iodine.",
  cook="Big enough to grill, small enough to go in a curry without dominating it. Garlic, butter, lime.",
  pair="Coconut curry, garlic, lime, pilau",
  faq=[("How many king prawns to a kilo?","Roughly 16–24."),
       ("Difference from jumbo?","Size alone — the species and handling are the same.")]),
"Prawns Tiger": dict(sci="Penaeus monodon", fam="Penaeidae",
  nut="~99 kcal · 21 g protein · 1 g fat · very high in selenium, iodine and B12",
  health="Lean, high-protein and rich in selenium and iodine.",
  cook="The all-purpose prawn — grill, fry, curry or boil. Striped shell, sweet firm meat.",
  pair="Garlic, chilli, coconut, pasta, pilau",
  faq=[("How many tiger prawns to a kilo?","Roughly 24–30."),
       ("Best value for a party?","Tiger is the sweet spot — big enough to look impressive, priced well below jumbo.")]),
"Prawns S1": dict(sci="Fenneropenaeus indicus", fam="Penaeidae",
  nut="~99 kcal · 21 g protein · 1 g fat · very high in selenium, iodine and B12",
  health="Lean, high-protein and rich in selenium and iodine.",
  cook="A good general-purpose prawn for curries, pilau and stir-fries.",
  pair="Coconut curry, pilau, garlic",
  faq=[("What does S1 mean?","It is a size grade — S1 is larger than S2 and smaller than tiger. Roughly 30–40 prawns to a kilo.")]),
"Prawns S2": dict(sci="Fenneropenaeus indicus", fam="Penaeidae",
  nut="~99 kcal · 21 g protein · 1 g fat · very high in selenium, iodine and B12",
  health="Lean, high-protein and rich in selenium and iodine.",
  cook="Everyday prawns for curry, rice dishes and seafood boils. The best value in the prawn range.",
  pair="Coconut curry, pilau, seafood boil",
  faq=[("What does S2 mean?","A size grade — roughly 40–50 prawns to a kilo. Smaller than S1, and priced accordingly.")]),
"Prawns Cocktail": dict(sci="Metapenaeus spp.", fam="Penaeidae",
  nut="~99 kcal · 21 g protein · 1 g fat · very high in selenium, iodine and B12",
  health="Lean, high-protein and rich in selenium and iodine.",
  cook="Small and quick. Perfect stirred through pilau or fried rice, folded into a curry at the last minute, or dressed cold for a prawn cocktail.",
  pair="Pilau, fried rice, mayonnaise, lime",
  faq=[("How small are they?","Small — 60 or more to a kilo. They cook in about a minute."),
       ("Best use?","Anywhere the prawn is an ingredient rather than the centrepiece — pilau, fried rice, pasta, salads.")]),
"Dried Anchovies": dict(sci="Stolephorus spp.", fam="Engraulidae",
  nut="~330 kcal · 60 g protein · 9 g fat · extremely high in calcium and protein by dry weight",
  health="Sun-drying concentrates everything. Weight for weight, dried anchovies are among the most protein- and calcium-dense foods you can keep in a cupboard.",
  cook="Fry crisp as a snack, or use a handful to build savoury depth in a stew or vegetable dish. Rinse briefly first if you want less salt.",
  pair="Ugali, sukuma wiki, tomato stew",
  faq=[("Do they need refrigeration?","No. Sealed, cool and dry is enough. Refrigerate only if your kitchen is very humid."),
       ("How long do they keep?","Six to twelve months if properly sealed and kept dry.")]),
"Dried Prawns": dict(sci="Penaeidae", fam="Sun-dried prawns",
  nut="~290 kcal · 62 g protein · 3 g fat · very high in calcium, protein and iodine by dry weight",
  health="Intensely concentrated protein and calcium, and a traditional coastal way of keeping seafood without refrigeration.",
  cook="Soak 15 minutes in warm water, then add to curries, pilau, coconut stews or vegetables. The soaking water is full of flavour — use it.",
  pair="Coconut stew, pilau, sukuma wiki, mchuzi",
  faq=[("Do I have to soak them?","For stews and curries, yes — 15 minutes in warm water. To use as a crunchy garnish, fry them dry."),
       ("How long do they keep?","Six months sealed and dry, longer in the fridge.")]),
"Dried Prawns — 1 kg": dict(sci="Penaeidae", fam="Sun-dried prawns",
  nut="~290 kcal · 62 g protein · 3 g fat · very high in calcium, protein and iodine by dry weight",
  health="Concentrated protein and calcium, shelf-stable without refrigeration.",
  cook="Soak 15 minutes in warm water, then add to curries, pilau or coconut stews.",
  pair="Coconut stew, pilau, sukuma wiki",
  faq=[("Why buy a kilo?","Restaurants, hotels and households that cook coastal food weekly. Sealed and dry, it keeps for six months.")]),
"Dried Sea Moss — Uncleaned": dict(sci="Eucheuma / Kappaphycus alvarezii", fam="Farmed red seaweed",
  meth="Farmed on lines in shallow water and sun-dried",
  loc="The seaweed farms of Kibuyuni and the Kenyan south coast — largely run by women's cooperatives",
  nut="Very low calorie · rich in iodine, magnesium, calcium and soluble fibre (carrageenan)",
  health="Sea moss is a natural source of iodine, magnesium and soluble fibre. It is a food, not a medicine — treat claims that it cures conditions with scepticism.",
  cook="Rinse thoroughly, soak 4–8 hours until it swells and softens, then blend with water into a gel. Stir the gel into smoothies, porridge, soups or juice.",
  pair="Smoothies, porridge, juice, soups",
  faq=[("What does uncleaned mean?","It comes as it was dried — you rinse away the salt and any sand yourself. It is cheaper for exactly that reason."),
       ("Where does it come from?","Farmed on the Kenyan south coast, much of it by women's cooperatives at Kibuyuni. Seaweed farming is one of the real success stories of Kenya's blue economy."),
       ("How do I make the gel?","Rinse, soak 4–8 hours until it swells, then blend with fresh water until smooth. Keeps in the fridge for two weeks.")]),
"Dried Sea Moss — Cleaned": dict(sci="Eucheuma / Kappaphycus alvarezii", fam="Farmed red seaweed",
  meth="Farmed on lines, sun-dried, then washed and sorted",
  loc="The seaweed farms of Kibuyuni and the Kenyan south coast",
  nut="Very low calorie · rich in iodine, magnesium, calcium and soluble fibre (carrageenan)",
  health="A natural source of iodine, magnesium and soluble fibre. A food, not a medicine.",
  cook="Soak 4–8 hours, blend into a gel, and stir into smoothies, porridge or soup.",
  pair="Smoothies, porridge, juice",
  faq=[("Why pay more for cleaned?","The salt and sand have already been washed out and the moss sorted. Less work for you, and less waste."),
       ("Does it taste of the sea?","Barely. Properly rinsed sea moss is close to flavourless — which is why it disappears into a smoothie.")]),
"Sea Moss Powder": dict(sci="Eucheuma / Kappaphycus alvarezii", fam="Milled dried seaweed",
  meth="Farmed, sun-dried, cleaned and milled",
  loc="The seaweed farms of the Kenyan south coast",
  nut="Very low calorie · rich in iodine, magnesium, calcium and soluble fibre",
  health="The same seaweed, milled fine. A food source of iodine and soluble fibre — not a medicine.",
  cook="No soaking. Stir a teaspoon straight into a smoothie, porridge, juice or soup. It also thickens gently as it stands.",
  pair="Smoothies, porridge, baking, soups",
  faq=[("How much do I use?","Start with a teaspoon a day. It thickens what you add it to, so more is not better."),
       ("Why choose powder over whole?","Convenience — no rinsing, no soaking, no blending.")]),
"Mangrove Honey": dict(sci="Apis mellifera scutellata", fam="Raw single-origin honey",
  meth="Hive-kept in the mangrove forests and harvested by hand",
  loc="The mangrove forests of the Kenyan south coast",
  nut="~304 kcal per 100 g · natural sugars, trace minerals and antioxidants",
  health="Raw, unheated honey with the distinctive dark, slightly salty character that mangrove flowers give. Never give honey to a child under one year old.",
  cook="Straight from the jar, over porridge, in tea, or as a glaze on grilled fish — the salt note works remarkably well with seafood.",
  pair="Porridge, tea, grilled fish, cheese",
  faq=[("Why does mangrove honey taste different?","Because the bees forage mangrove blossom, which gives a darker, richer honey with a faint salt-marsh note you will not find in an inland honey."),
       ("Does beekeeping help the mangroves?","Yes — it gives coastal communities an income that depends on the forest staying standing rather than being cut for timber or charcoal."),
       ("Will it crystallise?","Raw honey often does. Stand the jar in warm water to bring it back — never microwave it.")]),
"Red Snapper Fillets": dict(sci="Lutjanus spp.", fam="Lutjanidae — boneless fillet",
  nut="~100 kcal · 21 g protein · 1.3 g fat · high in selenium and B12",
  health="All the protein of whole snapper with no bones and no waste.",
  cook="Pan-fry skin-side down in a hot dry pan for crisp skin, or bake with lime and herbs. Thin fillets need 3–4 minutes total.",
  pair="Lime, garlic, herbs, salad, rice",
  faq=[("Why is fillet three times the whole price?","Because one kilo of fillet takes over two kilos of whole fish — filleting yields about 40–45% — plus the labour of cutting it by hand."),
       ("Skin on or off?","Your choice at checkout.")]),
"White Snapper Fillets": dict(sci="Lutjanus spp.", fam="Lutjanidae — boneless fillet",
  nut="~100 kcal · 21 g protein · 1.3 g fat · high in selenium and B12",
  health="Lean, boneless, high-protein white fish.",
  cook="Clean white flesh that suits any recipe. Pan-fry, bake, steam or poach in coconut.",
  pair="Coconut, lime, herbs, rice",
  faq=[("How is it different from red snapper fillet?","Same family, slightly milder and paler. Both are firm, boneless and mild.")]),
"Tilapia Fillets": dict(sci="Oreochromis niloticus", fam="Cichlidae — freshwater", imported=True,
  meth="Freshwater — farmed and lake-caught, not from our boats",
  loc="Kenyan freshwater. This is the one product besides salmon that does not come from the Indian Ocean, and we label it plainly.",
  nut="~96 kcal · 20 g protein · 1.7 g fat · high in protein, low in fat",
  health="Very lean, very mild and inexpensive — the easiest fish to introduce to children and to people who think they dislike fish.",
  cook="Pan-fry, bake or stew. Tilapia is mild to the point of neutral, so it takes on whatever you cook it with.",
  pair="Tomato stew, garlic, lemon, ugali",
  faq=[("Is tilapia from the ocean?","No — tilapia is a freshwater fish. We say so clearly because everything else we sell is Indian Ocean and traceable to Shimoni."),
       ("Why is it cheaper than snapper?","Freshwater tilapia is farmed at scale and costs less to produce than a hand-caught reef fish.")]),
"Filleting Service": dict(sci="", fam="Service",
  meth="Hand-filleted at our counter",
  loc="Mombasa",
  nut="", health="",
  cook="Choose your whole snapper from the day's catch and we fillet it for you by hand.",
  pair="",
  faq=[("How does this work?","You buy a whole snapper and we return it to you as boneless fillets. You are charged the filleted rate on the finished weight."),
       ("Do I get the frames back?","Yes if you want them — snapper heads and bones make an excellent stock or soup. Say so on WhatsApp.")]),
}
json.dump({"defaults":DEF,"content":C}, open("/tmp/content.json","w"), ensure_ascii=False, indent=1)
print("content entries:",len(C))
prods=json.load(open("/tmp/products.json"))
missing=[p['title'] for p in prods if p['title'] not in C]
print("products with NO content entry:",missing)
