# -*- coding: utf-8 -*-
"""Ocean Explorers — content source. Add species/creatures/lessons here; pages regenerate."""

FISH=[
 dict(slug="changu", en="Emperor Fish", sw="Changu", say="CHAH-ngoo", sci="Lethrinus spp.",
  img="changu.jpg", home="Coral reef",
  diet="Crabs, shellfish and small fish it crunches with strong back teeth",
  fun=["Emperors have thick lips and powerful jaws built for cracking shells.",
       "Many emperors start life as females and change into males as they grow older.",
       "They hunt mostly at dawn and dusk, and rest among the coral in between."],
  cons="Common on Kenyan reefs and caught by handline. Reef fish are slow to replace themselves, so size limits matter."),
 dict(slug="nguru", en="King Fish", sw="Nguru", say="ng-GOO-roo", sci="Scomberomorus commerson",
  img="nguru.jpg", home="Open water near the reef edge",
  diet="Sardines, anchovies and squid, chased at speed",
  fun=["A kingfish can swim in short bursts faster than most people can cycle.",
       "It has no swim bladder, so it must keep moving to stay off the bottom.",
       "Its silver sides carry faint wavy bars that fade the moment it leaves the water."],
  cons="A fast-growing ocean fish. Healthier stocks than slow reef species, but still fished hard across the region."),
 dict(slug="jodari", en="Tuna", sw="Jodari", say="jo-DAH-ree", sci="Thunnus albacares",
  img="jodari.jpg", home="The open ocean of the Pemba Channel",
  diet="Small fish, squid and crustaceans",
  fun=["Tuna are warm-blooded — unusual for a fish — which lets their muscles work harder.",
       "They never stop swimming, not even to sleep.",
       "A yellowfin tuna can cross an entire ocean in a single year."],
  cons="Tuna cross borders, so they are managed by countries working together through the Indian Ocean Tuna Commission."),
 dict(slug="pweza", en="Octopus", sw="Pweza", say="PWEH-zah", sci="Octopus cyanea",
  img="pweza.jpg", home="Holes and crevices in the coral reef",
  diet="Crabs, shellfish and small fish",
  fun=["An octopus has three hearts and blue blood.",
       "Two thirds of its neurons are in its arms, so each arm can partly think for itself.",
       "It can change colour and skin texture in under a second to vanish against a rock."],
  cons="Kenyan villages have tried closing octopus grounds for a few months at a time. When the area reopens, the octopus are bigger and there are more of them — a simple idea that works."),
 dict(slug="tafi", en="Rabbit Fish", sw="Tafi", say="TAH-fee", sci="Siganus sutor",
  img="tafi.jpg", home="Seagrass meadows",
  diet="Seagrass and algae — it is a grazer, like a goat of the sea",
  fun=["Rabbitfish have mildly venomous spines, so fishermen handle them carefully.",
       "They graze seagrass the way cattle graze a field, which keeps the meadow healthy.",
       "They often swim in pairs and stay together for a long time."],
  cons="One of the most abundant and fastest-growing fish on this coast, which makes it one of the more sustainable choices."),
 dict(slug="tewa", en="Grouper", sw="Tewa", say="TEH-wah", sci="Epinephelus spp.",
  img="tewa.jpg", home="Caves and overhangs in the reef",
  diet="Fish and crustaceans, swallowed whole in a sudden gulp",
  fun=["A grouper does not bite its prey — it opens its huge mouth so fast that water rushes in and carries the meal with it.",
       "Some groupers live for decades and stay in the same cave for years.",
       "Groupers and moray eels sometimes hunt together, which is rare between different species."],
  cons="Large groupers grow slowly and gather in the same place to spawn, which makes them easy to overfish. Small ones should be left to grow."),
 dict(slug="pono", en="Parrot Fish", sw="Pono", say="POH-noh", sci="Scarus spp.",
  img="pono.jpg", home="Coral reef",
  diet="Algae scraped off coral rock with a beak made of fused teeth",
  fun=["Parrotfish poo is sand. A single big one can produce hundreds of kilos of white sand a year.",
       "Some sleep inside a bubble of mucus they blow around themselves at night, which hides their smell from predators.",
       "Many change both colour and sex as they grow up."],
  cons="Parrotfish keep algae from smothering coral, so a reef with plenty of them recovers faster after bleaching."),
 dict(slug="simusimu", en="Sardine", sw="Simusimu", say="see-moo-SEE-moo", sci="Sardinella spp.",
  img="simusimu.jpg", home="Open water, in huge shoals",
  diet="Plankton — tiny drifting plants and animals",
  fun=["A shoal turns and flashes as one because each fish watches only its closest neighbours.",
       "Sardines are one of the few fish people eat whole, bones and all.",
       "They are food for almost everything bigger — tuna, kingfish, dolphins and seabirds."],
  cons="Small, fast-breeding and abundant. Eating small fish puts less pressure on the ocean than eating the big ones that hunt them."),
 dict(slug="papa", en="Shark", sw="Papa", say="PAH-pah", sci="Carcharhinus spp.",
  img="papa.jpg", home="Reef edges and open water",
  diet="Fish and squid",
  fun=["Sharks have no bones at all. Their whole skeleton is cartilage, the bendy stuff in your ear.",
       "Shark skin is covered in tiny tooth-like scales that make it rough as sandpaper.",
       "Sharks have swum in these oceans since long before there were trees on land."],
  cons="Many shark species are in serious trouble worldwide because they grow slowly and have few young. Several are protected in Kenya and must never be caught or sold."),
 dict(slug="ngisi", en="Squid", sw="Ngisi", say="ng-GEE-see", sci="Uroteuthis duvaucelii",
  img="ngisi.jpg", home="Open water, near the bottom by day",
  diet="Small fish and shrimp caught with two long tentacles",
  fun=["A squid moves by squirting water — the same idea as a jet engine.",
       "When frightened it releases ink and jets away behind the cloud.",
       "Squid have the largest eyes, for their body size, of almost any animal."],
  cons="Squid live fast and die young — usually within a year — so their numbers recover quickly."),
]

CREATURES=[
 dict(slug="dolphin", name="Dolphin", sw="Pomboo", say="pom-BOH-oh",
  sci="Tursiops aduncus · Indo-Pacific bottlenose",
  what="A dolphin is not a fish. It is a mammal, like you — it breathes air, is born alive, and drinks its mother's milk.",
  facts=["Dolphins find food using sound. They click, listen to the echo, and build a picture of what is ahead — even in dark water.",
   "Each dolphin has its own whistle, a bit like a name, and others use it to call that individual.",
   "Only half a dolphin's brain sleeps at a time. The other half keeps it swimming and breathing."],
  where="Pods live around Wasini Island and the Kisite–Mpunguti park, close to Shimoni.",
  protect="Protected in Kenya. We never catch or sell dolphins, and nor does any responsible fisherman."),
 dict(slug="turtle", name="Sea Turtle", sw="Kasa", say="KAH-sah",
  sci="Chelonia mydas · green turtle",
  what="A reptile that spends almost its whole life at sea, and comes ashore only to lay eggs in the sand.",
  facts=["A female returns to lay her eggs on the same beach where she herself hatched, sometimes decades later.",
   "The temperature of the sand decides whether the hatchlings are male or female — warmer sand makes more females.",
   "Green turtles graze seagrass, which keeps the meadow growing like a mown lawn."],
  where="Green and hawksbill turtles nest on Kenyan beaches, including the south coast near Shimoni.",
  protect="All sea turtles are protected in Kenya. Catching, selling or eating them is illegal. If you find a nest, tell a ranger or a Beach Management Unit."),
 dict(slug="coral", name="Coral Reef", sw="Matumbawe", say="mah-toom-BAH-weh",
  sci="Scleractinia · stony corals",
  what="Coral looks like a rock and is actually thousands of tiny animals living together, each one a bit like a miniature sea anemone.",
  facts=["Corals have algae living inside them. The algae make food from sunlight and share it — which is why coral needs clear, shallow water.",
   "When water gets too hot the coral pushes the algae out and turns white. That is called bleaching, and the coral is starving, not dead — yet.",
   "A reef the size of a classroom can shelter more kinds of animal than a whole field on land."],
  where="Fringing reefs run along most of the Kenyan coast, with protected reef inside Kisite–Mpunguti.",
  protect="Never stand on coral, and never take a piece home. It grows about as fast as your fingernails — a piece the size of your hand took years."),
 dict(slug="crab", name="Crab", sw="Kaa", say="KAH-ah",
  sci="Scylla serrata · mangrove mud crab",
  what="A crab wears its skeleton on the outside. To grow, it must climb out of its old shell entirely and grow a new one.",
  facts=["A crab that has just moulted is completely soft and hides until the new shell hardens.",
   "Crabs can regrow a lost claw over several moults.",
   "Mud crabs live among mangrove roots and are strong enough to crack a shell with one claw."],
  where="Mangrove creeks along the Kwale coast, including around Shimoni and Vanga.",
  protect="Small crabs and females carrying eggs should always go back. That is how there are crabs next year."),
 dict(slug="lobster", name="Spiny Lobster", sw="Kamba Mkubwa", say="KAHM-bah m-KOO-bwah",
  sci="Panulirus spp.",
  what="An Indian Ocean lobster has no big front claws — it defends itself with long spiny antennae and a powerful tail flick.",
  facts=["Lobsters sometimes walk across the seabed in long single-file queues, each touching the one in front.",
   "They can shoot backwards fast by snapping the tail underneath them.",
   "A lobster tastes and smells with its legs and antennae."],
  where="Reef holes and ledges around Shimoni and Wasini.",
  protect="Kenya sets a minimum size and closed seasons for lobster. Undersized lobsters must go back."),
 dict(slug="seahorse", name="Seahorse", sw="Farasi wa Bahari", say="fah-RAH-see wah bah-HAH-ree",
  sci="Hippocampus kuda",
  what="A seahorse is a fish, even though it does not look like one. It swims upright and very slowly.",
  facts=["It is the father who becomes pregnant. The female places her eggs in his pouch and he carries them until they hatch.",
   "A seahorse has no stomach, so it must eat almost constantly.",
   "Each eye moves separately, so it can watch for food and for danger at the same time."],
  where="Seagrass beds and sheltered shallow water along the coast.",
  protect="Seahorses are traded internationally and are protected under CITES rules. They are never something to collect."),
 dict(slug="ray", name="Ray", sw="Taa", say="TAH-ah",
  sci="Himantura, Mobula and others",
  what="A ray is a flat relative of the shark, with a skeleton of cartilage rather than bone.",
  facts=["Rays 'fly' through water by flapping their wide fins like wings.",
   "Many rest buried in sand with only their eyes showing.",
   "Manta rays are the biggest rays and eat nothing but plankton, filtering it as they swim."],
  where="Sandy flats, seagrass and open water along the coast.",
  protect="Manta and devil rays are protected. A stingray's barb is for defence, not attack — shuffle your feet in shallow sand and they simply move away."),
 dict(slug="starfish", name="Starfish", sw="Nyota ya Bahari", say="n-YOH-tah yah bah-HAH-ree",
  sci="Asteroidea",
  what="A sea star is not a fish at all. It has no brain and no blood, and moves on hundreds of tiny tube feet.",
  facts=["Many sea stars can regrow a whole arm, and a few can regrow an entire body from one arm.",
   "Some push their stomach out through their mouth to digest food outside their body.",
   "They 'see' with simple light-sensing eyespots on the tip of each arm."],
  where="Reef flats, rock pools and seagrass.",
  protect="Taking a sea star out of water to photograph it can kill it. Look, then leave it where it was."),
 dict(slug="mangrove", name="Mangrove Forest", sw="Mikoko", say="mee-KOH-koh",
  sci="Rhizophora mucronata and others",
  what="Trees that grow with their roots in salt water, standing on arching roots like stilts.",
  facts=["Mangroves filter salt out of seawater — some push it out through their leaves, which taste salty.",
   "Baby fish and prawns shelter among the roots where big predators cannot follow.",
   "Mangrove forests store more carbon per hectare than most forests on land."],
  where="Creeks and sheltered shores along the Kwale coast.",
  protect="Mangroves are cut for timber and charcoal. Beekeeping in mangrove forest gives people a reason to keep the trees standing — that is where our mangrove honey comes from."),
 dict(slug="seagrass", name="Seagrass Meadow", sw="Nyasi za Bahari", say="n-YAH-see zah bah-HAH-ree",
  sci="Thalassia, Cymodocea and others",
  what="Not seaweed — real flowering plants, with roots and seeds, growing underwater in meadows.",
  facts=["Seagrass makes oxygen, exactly like grass on land.",
   "It is the main food of green turtles and dugongs.",
   "Its roots hold the sand down, which stops beaches washing away in storms."],
  where="Shallow sandy areas between the beach and the reef, all along this coast.",
  protect="Seagrass is damaged by anchors and by boats running aground. It is one of the least noticed and most valuable habitats we have."),
]

LESSONS=[
 dict(slug="reef", title="Why coral reefs matter",
  q="What is a coral reef actually made of?",
  body=["A reef is built by tiny animals called polyps, each one smaller than a grain of rice. Each polyp builds a hard cup of limestone around itself. When it dies the cup remains, and the next generation builds on top. A reef is therefore a stack of skeletons, built up over thousands of years.",
   "Inside each polyp live microscopic algae. The algae capture sunlight and make sugar, and share it with the coral. In return the coral gives them a safe place to live. Neither does well alone.",
   "When the sea gets too warm, the coral expels its algae and turns bone white. This is bleaching. If the water cools soon enough the algae return; if not, the coral starves. Kenya's reefs bleached badly in 1998 and have bleached again since."],
  did="A reef covers less than one percent of the sea floor, yet roughly a quarter of all ocean species depend on reefs at some point in their lives."),
 dict(slug="mangroves", title="Mangroves: the forest in the sea",
  q="How can a tree live in salt water?",
  body=["Most plants die in salt water. Mangroves have three tricks: some block salt at the roots, some push it out through their leaves, and some dump it into old leaves and drop them.",
   "Their arching roots stand above the mud so the tree can breathe when the tide is in. Those same roots make a tangle that young fish and prawns hide in.",
   "Mangroves also protect the land. A belt of mangrove absorbs the force of a storm surge before it reaches houses behind it."],
  did="Mangrove forests store several times more carbon per hectare than tropical rainforest, most of it locked in the mud below."),
 dict(slug="seagrass", title="Seagrass: the underwater lawn",
  q="Is seagrass the same as seaweed?",
  body=["No. Seaweed is algae — no roots, no flowers, no seeds. Seagrass is a true flowering plant that returned to the sea about a hundred million years ago. It has roots, it flowers, and it makes seeds underwater.",
   "Seagrass meadows are nurseries. Many of the fish caught on this coast spent their early life hiding in seagrass before moving out to the reef.",
   "Green turtles graze it. Dugongs — very rare now in Kenya — eat almost nothing else."],
  did="Seagrass grows fast enough that a healthy meadow can bury carbon in its sediment for thousands of years."),
 dict(slug="tides", title="Tides: why the sea comes and goes",
  q="Why does the sea rise and fall twice a day?",
  body=["The Moon pulls on the ocean. Water on the side of Earth facing the Moon bulges towards it, and water on the opposite side bulges away. As Earth spins, each coast passes through both bulges — which is why this coast gets two high tides and two low tides roughly every day.",
   "The Sun pulls too, though less. When Sun and Moon line up, the pulls add together and you get very high and very low tides — spring tides. When they are at right angles the tides are gentler — neap tides.",
   "Fishermen here plan around the tide. Some grounds only fish well on a particular state of tide, and at spring low tide the reef flat is walkable."],
  did="At a big spring low tide on this coast you can walk out onto reef that is normally under two metres of water."),
 dict(slug="monsoon", title="Kaskazi and Kusi: the winds that rule the sea",
  q="Why does the ocean change through the year?",
  body=["Two monsoon winds shape life on the Swahili coast. The Kaskazi blows from the north-east roughly from November to March: gentle seas, clear water, good fishing.",
   "The Kusi blows from the south-east roughly from April to October. It is stronger, the sea is rougher, and small boats stay in more often.",
   "For centuries these winds carried sailing dhows between the East African coast, Arabia and India — out on one monsoon and home on the other. The Swahili language and coastal culture grew out of that traffic."],
  did="Before engines, a dhow captain could not simply come home when he chose. He waited for the wind to change, sometimes for months."),
 dict(slug="sustainable", title="What makes fishing sustainable?",
  q="Can you catch fish and still protect the sea?",
  body=["Yes — but only if you take less than the sea replaces. Three things decide it: how much you catch, what gear you use, and whether you let fish grow up and breed first.",
   "Gear matters enormously. A handline catches the fish that takes the hook. A bottom trawl drags a net across the seabed and takes everything, breaking the structure as it goes.",
   "Size matters too. A fish caught before it has bred once has contributed nothing to the next generation. Minimum sizes exist for exactly this reason.",
   "Some Kenyan communities close an area for a few months and then reopen it. The animals inside grow, breed, and spill out into the water around. Octopus closures on this coast have worked particularly well."],
  did="Small, fast-breeding fish like sardines and mackerel can be fished far harder than slow-growing reef fish like large groupers."),
 dict(slug="plastic", title="Plastic and the ocean",
  q="Where does plastic in the sea come from?",
  body=["Most of it starts on land. Rubbish dropped in a town washes into a drain, the drain runs to a river, and the river runs to the sea. Very little is dumped directly from ships.",
   "Sunlight and waves break plastic into smaller and smaller pieces. It does not disappear — it becomes microplastic, small enough for a fish to swallow by mistake.",
   "Lost fishing gear is a particular problem. A net that drifts free keeps catching things for months. That is called ghost fishing, and Kenyan fishermen have been testing nets tied with cotton twine that rots and lets the net fall apart."],
  did="Kenya banned single-use plastic carrier bags in 2017, one of the strictest such bans anywhere."),
 dict(slug="climate", title="A warmer ocean",
  q="How does climate change reach the sea?",
  body=["The ocean has absorbed most of the extra heat trapped by greenhouse gases. Warmer water bleaches coral, and it holds less dissolved oxygen, which fish need.",
   "The sea has also absorbed a large share of the carbon dioxide we have released. Dissolved in water, it makes the sea slightly more acidic, which makes it harder for corals and shellfish to build their skeletons and shells.",
   "Warmer water expands, and ice on land melts into the sea, so sea level rises. For a low coast with towns close to the water, that matters a great deal."],
  did="Reefs that still have plenty of grazing fish, like parrotfish, recover from bleaching faster than reefs where those fish have been fished out."),
]
